config/routes.rb
Smdb::Application.routes.draw do

  resources :movies

  resources :directors do
    resources :movies
  end

  # get "/directors/:director_id/movies" => 'movies#index', as: 'director_movies'
  # get "/directors/:director_id/movies/:id" => 'movies#show', as: 'director_movie'
  # get "/directors/:director_id/movies/new" => 'movies#show'
  # post "/directors/:director_id/movies" => 'movies#show'

  resources :reviews

  # Routes for sign-in/out
  get '/sessions/new' => 'sessions#new', :as => 'new_session'
  post '/sessions' => 'sessions#create', :as => 'sessions'
  delete '/sessions' => 'sessions#destroy', :as => 'session'

  root "movies#index"

  # Routes for the Actor resource:

  resources :actors
  resources :users
  resources :votes
  resources :roles
end

app/models/actor.rb
class Actor < ActiveRecord::Base
  # has many roles
  # def roles
  #   return Role.where(:actor_id => self.id)
  # end
  has_many :roles
  has_many :movies, :through => :roles
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :find_actor, :only => [:show, :edit, :update, :destroy]
  def find_actor
    @actor = Actor.find_by_id(params[:id])
  end

  def index
    @actors = Actor.all
  end

  def show
  end

  def new
    @actor = Actor.new
  end

  def create
    @actor = Actor.new
    @actor.name = params[:name]
    @actor.dob = params[:dob]
    @actor.bio = params[:bio]
    @actor.image_url = params[:image_url]

    if @actor.save
      redirect_to actors_url
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @actor.name = params[:name]
    @actor.dob = params[:dob]
    @actor.bio = params[:bio]
    @actor.image_url = params[:image_url]

    if @actor.save
      redirect_to actors_url
    else
      render 'new'
    end
  end

  def destroy
    @actor.destroy
    redirect_to actors_url
  end
end

app/views/actors/edit.html.erb
<h1>Editing Actor #<%= @actor.id %></h1>


<%= form_tag(actor_url(@actor), method: 'patch') do %>

  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name, @actor.name %>
  </div>

  <div>
    <%= label_tag :dob %><br />
    <%= text_field_tag :dob, @actor.dob %>
  </div>

  <div>
    <%= label_tag :bio %><br />
    <%= text_area_tag :bio, @actor.bio %>
  </div>

  <div>
    <%= label_tag :image_url %><br />
    <%= text_field_tag :image_url, @actor.image_url %>
  </div>

  
  <div>
    <%= submit_tag "Update Actor" %>
  </div>

<% end %>

app/views/actors/index.html.erb
<h1>Actors</h1>

<p><%= link_to 'Add a New Actor', new_actor_url %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date of Birth</th>
      <th>Bio</th>
      <th>Image</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @actors.each do |actor| %>
    <tr>
      <td><%= link_to actor.name, actor_url(actor.id) %></td>
      <td><%= actor.dob %></td>
      <td><%= truncate actor.bio %></td>
      <td><%= image_tag actor.image_url, width: 100 %></td>

      <td><%= link_to 'Show', actor_url(actor) %></td>
      <td><%= link_to 'Edit', edit_actor_url(actor) %></td>
      <td><%= link_to 'Destroy', actor_url(actor), method: 'delete', data: { confirm: "Do you really want to delete this actor?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/actors/new.html.erb
<h1>New Actor</h1>


<%= form_tag(actors_url, method: 'post') do %>


  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name %>
  </div>

  <div>
    <%= label_tag :dob %><br />
    <%= text_field_tag :dob %>
  </div>

  <div>
    <%= label_tag :bio %><br />
    <%= text_area_tag :bio %>
  </div>

  <div>
    <%= label_tag :image_url %><br />
    <%= text_field_tag :image_url %>
  </div>


  <div>
    <%= submit_tag "Create Actor" %>
  </div>
<% end %>

app/views/actors/show.html.erb
<h1>Actor #<%= @actor.id %></h1>

<p>
  <b>Name:</b>
  <%= @actor.name %>
</p>

<p>
  <b>Dob:</b>
  <%= @actor.dob %>
</p>

<p>
  <b>Bio:</b>
  <%= @actor.bio %>
</p>

<p>
  <b>Image:</b>
  <%= image_tag @actor.image_url %>
</p>

<p>
  <b>Filmography:</b>
  <ul>
    <% @actor.movies.each do |movie| %>
      <li><%= movie.title %></li>
    <% end %>
  </ul>
</p>