config/routes.rb
Smdb::Application.routes.draw do

  resources :movies

  resources :directors do
    resources :movies
  end

  # get "/directors/:director_id/movies" => 'movies#index', as: 'director_movies'
  # get "/directors/:director_id/movies/:id" => 'movies#show', as: 'director_movie'
  # get "/directors/:director_id/movies/new" => 'movies#show'
  # post "/directors/:director_id/movies" => 'movies#show'

  resources :reviews

  # Routes for sign-in/out
  get '/sessions/new' => 'sessions#new', :as => 'new_session'
  post '/sessions' => 'sessions#create', :as => 'sessions'
  delete '/sessions' => 'sessions#destroy', :as => 'session'

  root "movies#index"

  # Routes for the Actor resource:

  resources :actors
  resources :users
  resources :votes
  resources :roles
end

app/models/director.rb
class Director < ActiveRecord::Base
  # has many movies
  # def movies
  #   return Movie.where(:director_id => self.id)
  # end
  has_many :movies

  has_many :actors, :through => :movies

  validates_uniqueness_of :name
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  before_action :find_director, :only => [:show, :edit, :update, :destroy]
  def find_director
    @director = Director.find_by_id(params[:id])
  end

  def index
    @directors = Director.all
  end

  def show
  end

  def new
    @director = Director.new
  end

  def create
    @director = Director.new
    @director.name = params[:name]
    @director.dob = params[:dob]
    @director.image_url = params[:image_url]
    @director.bio = params[:bio]

    if @director.save
      redirect_to directors_url
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @director.name = params[:name]
    @director.dob = params[:dob]
    @director.image_url = params[:image_url]
    @director.bio = params[:bio]

    if @director.save
      redirect_to directors_url
    else
      render 'new'
    end
  end

  def destroy
    @director.destroy
    redirect_to directors_url
  end
end

app/views/directors/edit.html.erb
<h1>Editing Director #<%= @director.id %></h1>


<%= form_tag(director_url(@director), method: 'patch') do %>

  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name, @director.name %>
  </div>

  <div>
    <%= label_tag :dob %><br />
    <%= text_field_tag :dob, @director.dob %>
  </div>

  <div>
    <%= label_tag :image_url %><br />
    <%= text_field_tag :image_url, @director.image_url %>
  </div>

  <div>
    <%= label_tag :bio %><br />
    <%= text_area_tag :bio, @director.bio %>
  </div>

  
  <div>
    <%= submit_tag "Update Director" %>
  </div>

<% end %>

app/views/directors/index.html.erb
<h1>Directors</h1>

<p><%= link_to 'Add a New Director', new_director_url %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date of Birth</th>
      <th>Image</th>
      <th>Bio</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @directors.each do |director| %>
    <tr>
      <td><%= link_to director.name, director_url(director.id) %></td>
      <td><%= director.dob %></td>
      <td><%= image_tag director.image_url, width: 100 %></td>
      <td><%= truncate director.bio %></td>

      <td><%= link_to 'Show', director_url(director) %></td>
      <td><%= link_to 'Edit', edit_director_url(director) %></td>
      <td><%= link_to 'Destroy', director_url(director), method: 'delete', data: { confirm: "Do you really want to delete this director?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/directors/new.html.erb
<h1>New Director</h1>


<%= form_tag(directors_url, method: 'post') do %>


  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name %>
  </div>

  <div>
    <%= label_tag :dob %><br />
    <%= text_field_tag :dob %>
  </div>

  <div>
    <%= label_tag :image_url %><br />
    <%= text_field_tag :image_url %>
  </div>

  <div>
    <%= label_tag :bio %><br />
    <%= text_area_tag :bio %>
  </div>


  <div>
    <%= submit_tag "Create Director" %>
  </div>
<% end %>

app/views/directors/show.html.erb
<h1>Director #<%= @director.id %></h1>

<p>
  <b>Name:</b>
  <%= @director.name %>
</p>

<p>
  <b>Dob:</b>
  <%= @director.dob %>
</p>

<p>
  <b>Image:</b>
  <%= image_tag @director.image_url %>
</p>

<p>
  <b>Bio:</b>
  <%= @director.bio %>
</p>

<p>
  <b>Filmography:</b>
  <ul>
    <% @director.movies.each do |movie| %>
      <li>
        <%= movie.title %> (<%= movie.year %>)
        <ul>
          <% movie.actors.each do |actor| %>
            <li><%= actor.name %></li>
          <% end %>
        </ul>
      </li>
    <% end %>
  </ul>
</p>

<p>
  <b>Worked with:</b>
  <ul>
    <% @director.actors.each do |actor| %>
      <li><%= actor.name %></li>
    <% end %>
  </ul>
</p>