config/routes.rb
Smdb::Application.routes.draw do

  resources :movies

  resources :directors do
    resources :movies
  end

  # get "/directors/:director_id/movies" => 'movies#index', as: 'director_movies'
  # get "/directors/:director_id/movies/:id" => 'movies#show', as: 'director_movie'
  # get "/directors/:director_id/movies/new" => 'movies#show'
  # post "/directors/:director_id/movies" => 'movies#show'

  resources :reviews

  # Routes for sign-in/out
  get '/sessions/new' => 'sessions#new', :as => 'new_session'
  post '/sessions' => 'sessions#create', :as => 'sessions'
  delete '/sessions' => 'sessions#destroy', :as => 'session'

  root "movies#index"

  # Routes for the Actor resource:

  resources :actors
  resources :users
  resources :votes
  resources :roles
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :votes, :dependent => :destroy
  has_many :movies, :through => :votes

  has_secure_password

  validates :email, :presence => true, :uniqueness => true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, :only => [:show, :edit, :update, :destroy]
  before_action :current_user_must_be_user, :only => [:edit, :update, :destroy]

  def find_user
    @user = User.find_by_id(params[:id])
  end

  def current_user_must_be_user
    if current_user != @user
      redirect_to users_url, :notice => "Nice try."
    end
  end

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.name = params[:name]
    @user.email = params[:email]
    @user.password = params[:password]
    @user.password_confirmation = params[:password_confirmation]

    if @user.save
      # m = UserMailer.new
      email = UserMailer.welcome(@user)
      email.deliver
      # UserMailer.welcome.deliver!

      reset_session
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Signed up successfully."
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @user.name = params[:name]
    @user.email = params[:email]
    @user.password = params[:password]
    @user.password_confirmation = params[:password_confirmation]

    if @user.save
      redirect_to users_url
    else
      render 'new'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url
  end
end

app/views/users/edit.html.erb
<h1>Editing User #<%= @user.id %></h1>


<%= form_tag(user_url(@user), method: 'patch') do %>

  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name, @user.name %>
  </div>

  <div>
    <%= label_tag :email %><br />
    <%= text_field_tag :email, @user.email %>
  </div>

  <div>
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>

  <div>
    <%= label_tag :password_confirmation %><br />
    <%= password_field_tag :password_confirmation %>
  </div>

  <div>
    <%= submit_tag "Update User" %>
  </div>

<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<p><%= link_to 'Add a New User', new_user_url %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= link_to 'Show', user_url(user) %></td>
      <td>
        <% if user == current_user %>
          <%= link_to 'Edit', edit_user_url(user) %>
        <% end %>
      </td>
      <td>
        <% if user == current_user %>
          <%= link_to 'Destroy', user_url(user), method: 'delete', data: { confirm: "Do you really want to delete this user?" } %>
        <% end %>
      </td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |msg| %>
    <div class="alert alert-error">
      <a class="close" data-dismiss="alert">&times;</a>
      <%= msg %>
    </div>
  <% end %>
<% end %>


<%= form_tag(users_url, method: 'post') do %>


  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name %>
  </div>

  <div>
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>

  <div>
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>

  <div>
    <%= label_tag :password_confirmation %><br />
    <%= password_field_tag :password_confirmation %>
  </div>


  <div>
    <%= submit_tag "Create User" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>User #<%= @user.id %></h1>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>