config/routes.rb
Smdb::Application.routes.draw do

  resources :movies

  resources :directors do
    resources :movies
  end

  # get "/directors/:director_id/movies" => 'movies#index', as: 'director_movies'
  # get "/directors/:director_id/movies/:id" => 'movies#show', as: 'director_movie'
  # get "/directors/:director_id/movies/new" => 'movies#show'
  # post "/directors/:director_id/movies" => 'movies#show'

  resources :reviews

  # Routes for sign-in/out
  get '/sessions/new' => 'sessions#new', :as => 'new_session'
  post '/sessions' => 'sessions#create', :as => 'sessions'
  delete '/sessions' => 'sessions#destroy', :as => 'session'

  root "movies#index"

  # Routes for the Actor resource:

  resources :actors
  resources :users
  resources :votes
  resources :roles
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Smdb</title>

  <%= stylesheet_link_tag    "application", :media => "all" %>


  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet">

  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to "StarterMDB", root_url, :class => "brand" %>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Directors", directors_url %></li>
            <li><%= link_to "Movies", movies_url %></li>
            <li><%= link_to "Roles", roles_url %></li>
            <li><%= link_to "Actors", actors_url %></li>
            <li><%= link_to "Votes", votes_url %></li>
            <li><%= link_to "Users", users_url %></li>

            <%= form_tag movies_url, method: 'get', class: 'navbar-search pull-left' do %>
              <%= text_field_tag :search_term, "", class: 'search-query', placeholder: 'Search by Title..' %>
            <% end %>

          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <p>
      <% if current_user.present? %>
        Signed in as <%= current_user.email %>.
        <%= link_to "Sign Out", session_url, :method => 'delete' %>
      <% else %>
        <%= link_to "Sign in to vote", new_session_url %>
      <% end %>
    </p>

    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
        <a class="close" data-dismiss="alert">&times;</a>
        <%= msg %>
      </div>
    <% end %>

    <%= yield %>

  </div>

</body>
</html>